import type { Metadata } from "next";
import "./globals.css";
import { Ubuntu } from "next/font/google";
import Header from "./components/ui/header/Header";

const ubuntu = Ubuntu({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={ubuntu.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
